name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest  # Optimisé pour macOS
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: 'stable'
          architecture: x64  # Important pour macOS

      - name: Install Android SDK
        run: |
          brew install --cask android-commandlinetools
          echo "y" | sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Create key.properties
        run: |
          mkdir -p android
          echo "storePassword=\${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=\${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=\${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=../app/helloworld-keystore.jks" >> android/key.properties

      - name: Decode Keystore
        run: |
          mkdir -p android/app
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/helloworld-keystore.jks

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4  # Version corrigée
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
