name: Flutter iOS CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build IPA
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: 'stable'

      - name: Install CocoaPods
        run: |
          cd ios
          pod install
          cd ..

      - name: Build IPA
        run: flutter build ipa --release --no-codesign

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: iOS IPA
          path: build/ios/iphoneos/Runner.app
          retention-days: 7
